### PR TITLE
Feature/add time ago

### PR DESCRIPTION
**Pull request by richardoti**
Now "TimeAgo" string is always being shown instead of date.

### CODE REVIEW

**Comment by jgorset** [comment]
I like the interface — generally monkey patching is frowned upon in the Ruby world, though, how okay is it in Swift or Objective-C?

**Comment by richardoti** [comment]
Why this is a monkey-patch?

**Comment by jgorset** [comment]
Well, it's adding something to a class that is part of the standard library.

**Comment by jgorset** [comment]
I actually sort of like it, even in Ruby, mostly I'm just curious about how people see that in the Swift world.

**Comment by richardoti** [comment]
If you are about the way I extended NSDate, this feature exists in Objective-C world and is called Categories (Actually, in ObjC you could dynamically swap the execution of method, and add some code in-between that)

**Comment by jgorset** [comment]
Yep! So people are generally pretty okay with using categories, then, I guess?

**Comment by vadymmarkov** [comment]
Yes, categories in Objective-C and extensions in Swift are widely used :smiley:

**Comment by jgorset** [comment]
That's super cool, @vadymmarkov!

**Pull request merged**
